#=
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=#

function gen_fibs()
	fibs = Int64[1,2]
	while fibs[end] + fibs[end-1] < 4e6
		append!(fibs, fibs[end] + fibs[end-1])
	end
	return fibs
end

fibs = gen_fibs()

even_fibs = filter(iseven, fibs)

ans = sum(even_fibs)

println(ans)